apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customerules.rules.example.com
spec:
  group: rules.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            maxReplicas:
              type: integer
  scope: Namespaced
  names:
    plural: customrules
    singular: customrule
    kind: ReplicaLimit
    shortNames:
    - cr
